use eventsproject;

INSERT INTO OrganizedBy(name,founded) VALUES ("Opera Romana Timisoara",1875)
INSERT INTO OrganizedBy(name,founded) VALUES ("Filarmonica Banatul",1920)
INSERT INTO OrganizedBy(name, founded) VALUES ("Muzeul de Arta", 1879)
INSERT INTO OrganizedBy(name, founded) VALUES ("FABER",2018)
INSERT INTO OrganizedBy(name, founded) VALUES ("Vienna State Opera", 1861)
INSERT INTO OrganizedBy(name, founded) VALUES ("The Romanian National Theatre, Timisoara", 1882)
INSERT INTO OrganizedBy(name, founded) VALUES ("A&A Records", 2005)
INSERT INTO OrganizedBy(name, founded) VALUES ("Tate Modern",2000)
INSERT INTO OrganizedBy(name, founded) VALUES ("Miaudio",2010)
INSERT INTO OrganizedBy(name, founded) VALUES ("Mobius Gallery", 2015)
INSERT INTO OrganizedBy(name,founded) VALUES ("BMW",1916)
INSERT INTO OrganizedBy(name,founded) VALUES ("Asociatia Culturala Contrasens",2015)


INSERT INTO Address(name,streetName,number,phoneNumber,website) VALUES ("Opera Romana Timisoara","Piata Victoriei", 2, "+40256201284","www.ort.ro")
INSERT INTO Address(name,streetName,number,phoneNumber,website) VALUES ("Filarmonica Banatul ","C.D. Loga", 2, "+40256-492 521","www.filarmonicabanatul.ro")
INSERT INTO Address(name,streetName,number,phoneNumber,website) VALUES ("Muzeul de Arta","Piata Unirii ", 1, "+40256-491592","www.muzeuldeartatm.ro")
INSERT INTO Address(name,streetName,number,phoneNumber,website) VALUES ("FABER", "Penes Curcanul ", 4, "+40749 402 521","www.faber.ro")
INSERT INTO Address(name,streetName,number,phoneNumber,website) VALUES ("Parcul Rozelor", "Alexandru Borza", 1, "no phone ","no website ")


INSERT INTO event(name, eventType, localDate, address_id, ticketType, ticketPrice) VALUES ("Purcell's King Arthur",  "OPERA","2021-03-11", 1,"BUY_ONLINE",100.0 )
INSERT INTO event(name, eventType, localDate, address_id, ticketType, ticketPrice) VALUES ("The Little Prince",  "CHILDRENS_THEATRE_PLAY","2021-05-11", 1,"BUY_ONLINE",25.0 )
INSERT INTO event(name, eventType, localDate, address_id, ticketType, ticketPrice) VALUES ("Luna Amara- Live Concert",  "LIVE_MUSIC_CONCERT","2021-04-11", 4,"BUY_ONLINE",50.0 )
INSERT INTO event(name, eventType, localDate, address_id, ticketType, ticketPrice) VALUES ("Opening / Magdalena Abakanowicz: Presence, Essence, Identity",  "ART_OPENING","2021-03-21", 3,"FREE",0.0 )
INSERT INTO event(name, eventType, localDate, address_id, ticketType, ticketPrice) VALUES ("Trip hop Party",  "PARTY","2021-05-11", 5,"FREE",0.0)
INSERT INTO event(name, eventType, localDate, address_id, ticketType, ticketPrice) VALUES ("Vivaldi's Four Seasons", "CLASSICAL_MUSIC_CONCERT","2021-03-11", 2,"BUY_ONLINE",25.0 )
INSERT INTO event(name, eventType, localDate, address_id, ticketType, ticketPrice) VALUES ("King Lear",  "THEATRE_PLAY","2021-03-21", 1,"BUY_ONLINE",100.0 )
INSERT INTO event(name, eventType, localDate, address_id, ticketType, ticketPrice) VALUES ("Folk music and dancing",  "LIVE_MUSIC_CONCERT","2021-06-11", 5,"FREE",0.0 )
INSERT INTO event(name, eventType, localDate, address_id, ticketType, ticketPrice) VALUES ("Cornelia Parker's 'Cold Dark Matter: An Exploded View' ", "MUSEUM_EXHIBITION","2021-03-11", 3,"FREE",0.0 )
INSERT INTO event(name, eventType, localDate, address_id, ticketType, ticketPrice) VALUES ("BMW launches a new car model",  "LAUNCHING_PARTY","2021-03-11", 3,"FREE",0.0 )
INSERT INTO event(name, eventType, localDate, address_id, ticketType, ticketPrice) VALUES ("Hamlet",  "THEATRE_PLAY","2021-03-19", 1,"BUY_TICKET_ON_THE_SPOT",100.0 )
INSERT INTO event(name, eventType, localDate, address_id, ticketType, ticketPrice) VALUES ("Corneliu Baba",  "MUSEUM_EXHIBITION","2021-04-01", 3,"FREE",0.0 )
INSERT INTO event(name, eventType, localDate, address_id, ticketType, ticketPrice) VALUES ("Vincent",  "CHILDRENS_THEATRE_PLAY","2021-05-11", 1,"BUY_TICKET_ON_THE_SPOT",25.0 )
INSERT INTO event(name, eventType, localDate, address_id, ticketType, ticketPrice) VALUES ("PIAZZOLLA Four Seasons of Buenos Aires",  "CLASSICAL_MUSIC_CONCERT","2021-04-22", 2,"BUY_TICKET_ON_THE_SPOT",50.0 )
INSERT INTO event(name, eventType, localDate, address_id, ticketType, ticketPrice) VALUES ("Hyperliteratura launches a new book",  "LAUNCHING_PARTY","2021-05-15", 3,"FREE",0.0 )

insert into organizedBy_event (event_id, organizedBy_id) values (1, 1)
insert into organizedBy_event (event_id, organizedBy_id) values (1, 5)
insert into organizedBy_event (event_id, organizedBy_id) values (2, 6)
insert into organizedBy_event (event_id, organizedBy_id) values (3, 4)
insert into organizedBy_event (event_id, organizedBy_id) values (3, 7)
insert into organizedBy_event (event_id, organizedBy_id) values (4, 3)
insert into organizedBy_event (event_id, organizedBy_id) values (4, 8)
insert into organizedBy_event (event_id, organizedBy_id) values (4, 10)
insert into organizedBy_event (event_id, organizedBy_id) values (5, 9)
insert into organizedBy_event (event_id, organizedBy_id) values (6, 2)
insert into organizedBy_event (event_id, organizedBy_id) values (7, 6)
insert into organizedBy_event (event_id, organizedBy_id) values (8, 9)
insert into organizedBy_event (event_id, organizedBy_id) values (9, 8)
insert into organizedBy_event (event_id, organizedBy_id) values (9, 12)
insert into organizedBy_event (event_id, organizedBy_id) values (10, 11)
insert into organizedBy_event (event_id, organizedBy_id) values (11, 6)
insert into organizedBy_event (event_id, organizedBy_id) values (11, 2)
insert into organizedBy_event (event_id, organizedBy_id) values (11, 11)
insert into organizedBy_event (event_id, organizedBy_id) values (12, 3)
insert into organizedBy_event (event_id, organizedBy_id) values (12, 12)
insert into organizedBy_event (event_id, organizedBy_id) values (13, 6)
insert into organizedBy_event (event_id, organizedBy_id) values (14, 2)
insert into organizedBy_event (event_id, organizedBy_id) values (15, 12)
