package ro.itschool.curs.enums;

public enum EventType {
	OPERA ,CHILDRENS_THEATRE_PLAY, LIVE_MUSIC_CONCERT ,MUSEUM_EXHIBITION,   PARTY, CLASSICAL_MUSIC_CONCERT , THEATRE_PLAY ,  LAUNCHING_PARTY,
	CHILDRENS_SHOW , 
	ART_OPENING,
	FAIR;
	
}
